# Generated by Django 4.1.8 on 2023-04-28 22:51

from django.db import migrations, models
import django.db.models.deletion
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_title',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_image', to='wagtailimages.image'),
        ),
    ]
