# Generated by Django 4.1.8 on 2024-10-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='translation_type',
            new_name='translation_source',
        ),
    ]
