# Generated by Django 3.2.10 on 2021-12-12 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('country', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(blank=True, max_length=250)),
                ('translation_type', models.CharField(blank=True, max_length=50)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('english_name', models.CharField(max_length=1000)),
                ('arabic_name', models.CharField(max_length=1000)),
                ('transliteration', models.CharField(max_length=1000)),
                ('total_verses', models.IntegerField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('iso_code', models.CharField(max_length=50)),
                ('direction', models.IntegerField()),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('vtext', models.CharField(max_length=10000)),
                ('enabled', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='quran.author')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='quran.chapter')),
                ('vlang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verse_language', to='quran.language')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='alang',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_language', to='quran.language'),
        ),
    ]
